name: Build and Deploy .NET Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4 # Actualizado para Node 24

    - name: Set up .NET
      uses: actions/setup-dotnet@v4 # Actualizado para Node 24
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration Release --no-restore

    - name: Publish application
      # Se especifica el proyecto exacto (.csproj) en lugar de la solución (.sln) para permitir el parámetro --output
      run: dotnet publish Lab08-ValeriaZumaran/Lab08-ValeriaZumaran.csproj --configuration Release --output ./published --no-build

    - name: Deploy to server
      run: |
        scp -r ./published username@server:/path/to/deploy



